### ISSUE TITLE
Cant interact with Selectbox while someone is typing

### ISSUE THREAD

**Issue by Jannik-Baar** [Rishabh-malhotraa/caucus#2]
If I try to interact with a selectbox while someone is typing it closes the selectbox again

**Comment by Rishabh-malhotraa** [comment]
Okay, I'll change the behavior so it only closes when you click it out of focus, but I feel that's what it does right now because if someone types something it the select box becomes out of focus and it closes. I look into seeing what are the better ways of implementing this.

**Comment by Jannik-Baar** [comment]
No, I mean that the Selectbox closes for me, when someone else is typing
