### ISSUE TITLE
Improving Contrast on hover

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Rishabh-malhotraa/caucus#30]
Currently, there is no contrast on hover on list items.

![image](https://user-images.githubusercontent.com/54576074/123245304-5228f980-d502-11eb-81cb-e16902854ce1.png)

![image](https://user-images.githubusercontent.com/54576074/123245396-6967e700-d502-11eb-8875-d1dbb512afd6.png)

**Comment by Deepakmukka1** [comment]
@Rishabh-malhotraa In order to create a branch should i follow feature/featureName or should i follow different , because this is enhancement

**Comment by Deepakmukka1** [comment]
@Rishabh-malhotraa  @iamdevvalecha  I cannot load the problems list in my local machine , is there any server should i start 


![image](https://user-images.githubusercontent.com/56472120/131951228-244be5e8-7097-4dc7-b667-bcac618489aa.png)

**Comment by Rishabh-malhotraa** [comment]
Hi, @Deepakmukka1 thanks for showing interest in caucus,
You need to download and set up [cacus server](https://github.com/Rishabh-malhotraa/caucus-server), if you have any other problem setting the project up,  you can dm me on discord (rishabh.malhotra#4193) and I can call you and walk you through setting it up, besides that, i'll update the `installation.md` file as its been deprecated and is no longer valid

**Comment by Deepakmukka1** [comment]
Thank you , I ll try setting up asap

**Comment by Rishabh-malhotraa** [comment]
Hey @dipenr06 sure, go right ahead, you can hmu on discord if you have any problem

**Comment by chirag3003** [comment]
@Rishabh-malhotraa can u assign me this issue, I would like to work on this

**Comment by chirag3003** [comment]
![hover-screenshot](https://user-images.githubusercontent.com/68195580/135572332-cc715c16-bf64-42bf-bf91-191c0add8ca1.png)

**Comment by ArpitBirSingh** [comment]
Can I raise a pull request for this issue ?? @Rishabh-malhotraa

**Comment by Khushi-Shukla** [comment]
Can you assign this issue to me?

**Comment by Rishabh-malhotraa** [comment]
Hey @gabriellend, it's been fixed. I will deploy the changes to Heroku by the end of the week.
