### ISSUE TITLE
Code duplication when joining

### ISSUE THREAD

**Issue by StratusFearMe21** [Rishabh-malhotraa/caucus#6]
Hello! It's that guy you were talking to from DogeHouse. I didn't have time to tell you this but based on my knowledge of the Web socket protocol. I think the reason that this is happening is because when someone new joins a room, the server has to send the current state of the room to the new user, So it sends the whole thing across the websocket, but instead of sending the code to just that user, it broadcasts the packet to everyone in the room, duplicating the current code to all user in the room. I can't seem to duplicate this though so this might be a little difficult

**Comment by Rishabh-malhotraa** [comment]
Okay yes, I do broadcast the message to all the users when a new user joins in, that could be the reason for this. but what I don't understand is it works perfectly fine on my localhost which is so confusing


https://user-images.githubusercontent.com/54576074/111921131-deb5bd00-8ab8-11eb-87e9-edfc6f3c3e79.mp4

In the end, the user is redirected to the login page because I have like 4 person limit per room

**Comment by StratusFearMe21** [comment]
New development, this is a chrome specific problem. I got it to duplicate using chrome instead of firefox!

**Comment by StratusFearMe21** [comment]
I think I found the problem, it's sending the same code twice under different headers
![image](https://user-images.githubusercontent.com/57533634/111921385-a5eef700-8a6a-11eb-8b9a-fc21009c35b4.png)

**Comment by Rishabh-malhotraa** [comment]
Okay I get the problem, when a new user joins, I am emitting the event to everyone in the room, I just need to send this to the user who joined 

``` js
    socket.on("send-message", (body: MessageProps) => {
      const roomID = body.userInfo.roomID;
      body.socketID = socket.id;
      socket.broadcast.to(roomID).emit("message", body);
    });
```

**Comment by firasjaber** [comment]
hello, that's how i reproduced the bug 
![caucus_bug_reproduce](https://user-images.githubusercontent.com/41070156/111922418-f0d43300-8a99-11eb-8f7a-9eba08dcfe59.gif)

**Comment by Rishabh-malhotraa** [comment]
Thanks @firasjaber , another reason I feel this could be happening is when I checked the network tab in the chrome dev tool all I don't see socket connection but xhr polling for some reason, but that is not the case in localhost, it could be a Heroku specific problem in which sockets connection is not being established, I'll try somethings and try to fix this asap
