### ISSUE TITLE
Move Hosting from Heroku to GCP or DIgital Ocean

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Rishabh-malhotraa/caucus#7]
There deployment experience with Heroku hasn't been great at all, I am having bugs when I deploy it on the Heroku server and not on my localhost which is very annoying and difficult to debug, I either plan to dockerize the serve or switch to either GCP or Digital ocean.

**Comment by HarrisonMayotte** [comment]
If you need someone to handle some infrastructure stuff I can do that for ya.

**Comment by Rishabh-malhotraa** [comment]
Do you have any experience with docker and nginx?

**Comment by HarrisonMayotte** [comment]
Still learning docker but I'm familiar with nginx

**Comment by HarrisonMayotte** [comment]
If you want to do a discord call to discuss further my discord is HarrisonMayotte#5960.
