### ISSUE TITLE
Login using providers is not working on local

### ISSUE THREAD

**Issue by taksuparth** [Rishabh-malhotraa/caucus#75]
**Describe the bug**
Login using providers is not working.

**To Reproduce**
1. On the Login page click on Google or Github

**Expected behavior**
- It should redirect to GitHub or Google's authentication.

**Additional context**
generated URL is incorrect. In ```caucus/src/pages/Login/Login.tsx``` `handleLogin` function is creating URL as `${backend_URL}/auth/${provider}` but the provider is given as `/google` `/github` making incorrect request as ```${backend_URL}/auth//google``` instead of ```${backend_URL}/auth/google```

**Comment by taksuparth** [comment]
@Rishabh-malhotraa Please check

**Comment by Rishabh-malhotraa** [comment]
Thanks for raising the issue @taksuparth , I'll take a look

**Comment by taksuparth** [comment]
Closing this issue as fix for this is merged!
