### ISSUE TITLE
Local Development Server crashing upon clicking `Run Code`

### ISSUE THREAD

**Issue by prayutsu** [Rishabh-malhotraa/caucus#80]
**Describe the bug**

Add a code snippet in editor.

**To Reproduce**
1. Join a public room on a local development server.
2. Write a code snippet in the editor.
3. Click run code.
4. Notice the server is crashed and the loading continues in the output section.

**Expected behavior**
The app shouldn't crash and the program should compile successfully.

**Screenshots**

<img width="1108" alt="Screenshot 2022-03-02 at 10 55 35 PM" src="https://user-images.githubusercontent.com/54636525/156415716-acb81e6a-24c9-49d0-ab39-fafee2c550f6.png">
<img width="1433" alt="Screenshot 2022-03-02 at 11 00 05 PM" src="https://user-images.githubusercontent.com/54636525/156415790-c4303614-02f7-4f93-bbc3-f609957f9d57.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac os
 - Browser [e.g. chrome, safari] Brave

**Smartphone (please complete the following information):**

**Additional context**

**Comment by prayutsu** [comment]
@Rishabh-malhotraa I made the changes you mentioned - 
1. Created a .env file 
2. Put JDOODLE_SECRETS in it.
3. Updated JDOODLE_URL (took a pull from main).

But the app is getting crashed when I am clicking on run code button.
<img width="1120" alt="Screenshot 2022-03-06 at 10 14 56 PM" src="https://user-images.githubusercontent.com/54636525/156932969-d2133438-6599-4c76-b195-77c623652925.png">
<img width="1440" alt="Screenshot 2022-03-06 at 10 15 03 PM" src="https://user-images.githubusercontent.com/54636525/156932973-c6ac3e53-5669-47c1-b69e-671f1638b285.png">

**Comment by prayutsu** [comment]
Why it is returning an unauthorized status code?

**Comment by Rishabh-malhotraa** [comment]
> Why it is returning an unauthorized status code?

I you are getting unauthorized, that means your tokens are incorrect, can you recheck your tokens, you  require two of them

**Comment by prayutsu** [comment]
@Rishabh-malhotraa I doubted same, and I therefore checked the secrets 4-5 times.

My .env file
```
JDOODLE_CLIENTID=832e180ceafc5633a65a66e23fb22ad4
JDOOLDE_CLIENTSECRET=e310c26040828fdfa6eb3958cbd205310095937f2d552ea0e3e37b12a0ea2e2b
```

This is what I get from JDOODLE credentials tab - 
Client ID 
832e180ceafc5633a65a66e23fb22ad4
Client Secret 
e310c26040828fdfa6eb3958cbd205310095937f2d552ea0e3e37b12a0ea2e2b

I believe that they both are the same.

**Comment by prayutsu** [comment]
I also tried refreshing credentials and getting a new client secret but the error remains the same.

**Comment by Rishabh-malhotraa** [comment]
I think it's your still your credential keys issue you can try getting your keys from a different account

for now, you can use these keys, but I'll refresh them tomorrow so you would not be able to use them after tomorrow, so maybe try getting the keys from a different account.

```
JDOODLE_CLIENTID=da358ecadea106b681e17e6dd1194863
JDOOLDE_CLIENTSECRET=7b69d6ce85668cb6fe5dbd61d37433bf3ffe31c14fed906833faad7e2593f5ca
```

**Comment by prayutsu** [comment]
Unfortunately, I am getting the same error even if I tried the credentials provided above.
![Uploading Screenshot 2022-03-06 at 11.49.48 PM.png…]()

**Comment by Rishabh-malhotraa** [comment]
you need to restart the server once you update the env file

**Comment by prayutsu** [comment]
> you need to restart the server once you update the env file

Actually I did restart the server several times.

**Comment by prayutsu** [comment]
Also, one more thing to note is that if I click run code on empty code, it doesn't throw any error. That means -

We are reaching out to some part of the the /execute endpoint - 
```javascript
router.post("/execute", async (req, res) => {
  const { script, language, stdin } = req.body;
  if (!language || !script) {
    return res.status(200).json({
      message: "Code should not be empty and Language undefined",
    });
  }

  const response = await axios({
    method: "POST",
    url: `${JDOODLE_URL}/execute`,
    data: {
      script: script,
      stdin: stdin,
      language: getLanguage[language],
      versionIndex: getLanguageVersion[language],
      clientId: JDOODLE.clientID,
      clientSecret: JDOODLE.clientSecret,
    },
    responseType: "json",
  });
  res.json(response.data);
});
```

**Comment by prayutsu** [comment]
@Rishabh-malhotraa Did you get a chance to investigate further?

**Comment by Rishabh-malhotraa** [comment]
Can you try running on incognito and maybe do a  reinstall of Caucus with latest commit(don't add any env file in the clean install as the config file contains the credentials now)

**Comment by prayutsu** [comment]
> Can you try running on incognito and maybe do a reinstall of Caucus with the latest commit(don't add any env file in the clean install as the config file contains the credentials now)

<img width="1437" alt="Screenshot 2022-03-11 at 10 41 59 PM" src="https://user-images.githubusercontent.com/54636525/157914780-c69c0cc1-b91e-4907-85dd-5d4d4c4d676e.png">

This finally worked. Thanks, @Rishabh-malhotraa for helping me set up the project.
